services:
  multimind:
    build:
      dockerfile: Dockerfile.private-dna
      secrets:
        - github_token

secrets:
  github_token:
    file: ${MULTIMIND_GITHUB_TOKEN_FILE:-./.secrets/github_token}
