"""
MultiMind AI - Real Design DNA Proofs (S6.2)
Defines three asset-free, contrasting Design DNA definitions mapping supported semantic capabilities.
"""
from ui.dna.models import DesignDNA

# DNA A — Japan Print / Ink
JAPAN_PRINT_INK_DNA = DesignDNA(
    id="japan-print-ink",
    display_name="Japan Print / Ink",
    category="cultural",
    description="A restrained, print-inspired visual character drawing on ink strokes and warm paper surfaces.",
    reference_identity="Traditional Japanese woodblock printing and high-contrast editorial typography",
    visual_character="restrained, ink-oriented, editorial, tactile paper direction",
    color_direction="warm paper background, dark ink text, restrained cinnabar accents",
    typography_direction="deliberate, high contrast print hierarchy",
    surface_language="paper-like surface and subtle warm borders",
    shape_language="firm, small radii reflecting cut block edges",
    interaction_character="precise, restrained focus and active state contrast",
    materials=[],
    provenance={
        "author": "MultiMind Design Team",
        "license": "MIT",
        "source": "S6.2 Design DNA Proofs",
        "attribution": "Inspired by traditional woodblock and print graphic arts",
    },
    colors={
        "background": "#F5F2EB",
        "surface": "#EAE5D9",
        "surface_elevated": "#DFD9C9",
        "surface_muted": "#F5F2EB",
        "surface_hover": "#E2DCCE",
        "surface_input": "#EFECE2",
        "text": "#121212",
        "text_muted": "#55524C",
        "text_disabled": "#8C8880",
        "primary": "#121212",
        "primary_hover": "#2B2B2B",
        "primary_active": "#000000",
        "secondary": "#55524C",
        "secondary_hover": "#3D3A35",
        "accent": "#C83E2B",  # Cinnabar Red
        "border": "#222222",
        "border_subtle": "#D1CBBF",
        "border_hover": "#121212",
        "border_focus": "#C83E2B",
        "focus_ring": "rgba(200, 62, 43, 0.3)",
        "success": "#2D6A4F",
        "success_bg": "rgba(45, 106, 79, 0.12)",
        "warning": "#B5651D",
        "warning_bg": "rgba(181, 101, 29, 0.12)",
        "danger": "#C83E2B",
        "danger_bg": "rgba(200, 62, 43, 0.12)",
        "info": "#121212",
        "info_bg": "rgba(18, 18, 18, 0.08)",
    },
    typography={
        "font_family_base": "Georgia, 'Times New Roman', Times, serif",
        "font_family_mono": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
        "roles": {
            "display": {"size": "2.125rem", "weight": "700", "line_height": "1.25"},
            "heading": {"size": "1.5rem", "weight": "700", "line_height": "1.3"},
            "subheading": {"size": "1.2rem", "weight": "600", "line_height": "1.35"},
            "body": {"size": "1rem", "weight": "400", "line_height": "1.6"},
            "body_small": {"size": "0.875rem", "weight": "400", "line_height": "1.5"},
            "caption": {"size": "0.75rem", "weight": "400", "line_height": "1.4"},
            "label": {"size": "0.875rem", "weight": "600", "line_height": "1.2"},
        },
    },
    spacing={
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "2xl": "3rem",
    },
    radius={
        "none": "0px",
        "sm": "2px",
        "md": "2px",
        "lg": "4px",
        "pill": "9999px",
    },
)


# DNA B — Chainsaw Man-Inspired
CHAINSAW_MAN_INSPIRED_DNA = DesignDNA(
    id="chainsaw-man-inspired",
    display_name="Chainsaw Man Inspired",
    category="anime",
    description="An aggressive, graphic, poster-like urban visual character with stark contrast and sharp geometry.",
    reference_identity="High-energy manga composition, urban editorial graphic direction, and sharp contrasts",
    visual_character="aggressive, graphic, urban poster, rough, sharp, high contrast",
    color_direction="stark dark asphalt surface, intense safety yellow and visceral red accents",
    typography_direction="assertive, bold, graphic editorial hierarchy",
    surface_language="stark dark slate/asphalt surfaces with razor-sharp borders",
    shape_language="sharp, zero-radius geometry",
    interaction_character="high-contrast assertive interactive states",
    materials=[],
    provenance={
        "author": "MultiMind Design Team",
        "license": "MIT",
        "source": "S6.2 Design DNA Proofs",
        "attribution": "Conceptual interpretation of modern urban action manga visual language",
    },
    colors={
        "background": "#0D0D11",
        "surface": "#16161D",
        "surface_elevated": "#22222E",
        "surface_muted": "#0D0D11",
        "surface_hover": "#2A2A38",
        "surface_input": "#111116",
        "text": "#F2F2F5",
        "text_muted": "#9A9AA6",
        "text_disabled": "#5A5A66",
        "primary": "#FFCC00",  # Caution / Hazard Yellow
        "primary_hover": "#FFE066",
        "primary_active": "#E6B800",
        "secondary": "#9A9AA6",
        "secondary_hover": "#CCCCCC",
        "accent": "#E63946",  # Visceral Red
        "border": "#333344",
        "border_subtle": "#22222E",
        "border_hover": "#FFCC00",
        "border_focus": "#FFCC00",
        "focus_ring": "rgba(255, 204, 0, 0.4)",
        "success": "#10B981",
        "success_bg": "rgba(16, 185, 129, 0.15)",
        "warning": "#FFCC00",
        "warning_bg": "rgba(255, 204, 0, 0.15)",
        "danger": "#E63946",
        "danger_bg": "rgba(230, 57, 70, 0.18)",
        "info": "#FFCC00",
        "info_bg": "rgba(255, 204, 0, 0.12)",
    },
    typography={
        "font_family_base": "'Impact', 'Arial Black', -apple-system, BlinkMacSystemFont, sans-serif",
        "font_family_mono": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
        "roles": {
            "display": {"size": "2.25rem", "weight": "900", "line_height": "1.15"},
            "heading": {"size": "1.5rem", "weight": "800", "line_height": "1.2"},
            "subheading": {"size": "1.25rem", "weight": "700", "line_height": "1.3"},
            "body": {"size": "1rem", "weight": "400", "line_height": "1.45"},
            "body_small": {"size": "0.875rem", "weight": "400", "line_height": "1.4"},
            "caption": {"size": "0.75rem", "weight": "600", "line_height": "1.3"},
            "label": {"size": "0.875rem", "weight": "700", "line_height": "1.2"},
        },
    },
    spacing={
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "0.875rem",
        "lg": "1.25rem",
        "xl": "1.75rem",
        "2xl": "2.5rem",
    },
    radius={
        "none": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "pill": "0px",
    },
)


# DNA C — Mushishi-Inspired
MUSHISHI_INSPIRED_DNA = DesignDNA(
    id="mushishi-inspired",
    display_name="Mushishi Inspired",
    category="anime",
    description="A calm, organic, atmospheric visual character with muted earth/moss tones and gentle curves.",
    reference_identity="Atmospheric naturalism, quiet organic stillness, and soft muted color palettes",
    visual_character="calm, organic, atmospheric, muted, natural, restrained",
    color_direction="deep forest moss background, muted sage surfaces, calm green tea accents",
    typography_direction="calm, readable, unobtrusive typography",
    surface_language="soft natural surface layering with organic subtle borders",
    shape_language="softer rounded geometry",
    interaction_character="gentle, unobtrusive interactive state transitions",
    materials=[],
    provenance={
        "author": "MultiMind Design Team",
        "license": "MIT",
        "source": "S6.2 Design DNA Proofs",
        "attribution": "Conceptual interpretation of naturalistic anime atmospheric art",
    },
    colors={
        "background": "#111814",
        "surface": "#1D2822",
        "surface_elevated": "#293830",
        "surface_muted": "#111814",
        "surface_hover": "#24322A",
        "surface_input": "#16201B",
        "text": "#E2EBE5",
        "text_muted": "#91A398",
        "text_disabled": "#5A6B60",
        "primary": "#7A9A8B",  # Muted Green Tea
        "primary_hover": "#8EAFA0",
        "primary_active": "#668576",
        "secondary": "#91A398",
        "secondary_hover": "#B0C2B7",
        "accent": "#A3B899",  # Soft Pale Moss Accent
        "border": "#2C3E34",
        "border_subtle": "#1D2822",
        "border_hover": "#3F5649",
        "border_focus": "#7A9A8B",
        "focus_ring": "rgba(122, 154, 139, 0.3)",
        "success": "#668576",
        "success_bg": "rgba(102, 133, 118, 0.15)",
        "warning": "#C2A675",
        "warning_bg": "rgba(194, 166, 117, 0.15)",
        "danger": "#B86B6B",
        "danger_bg": "rgba(184, 107, 107, 0.15)",
        "info": "#7A9A8B",
        "info_bg": "rgba(122, 154, 139, 0.12)",
    },
    typography={
        "font_family_base": "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        "font_family_mono": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
        "roles": {
            "display": {"size": "2rem", "weight": "500", "line_height": "1.3"},
            "heading": {"size": "1.5rem", "weight": "500", "line_height": "1.35"},
            "subheading": {"size": "1.25rem", "weight": "500", "line_height": "1.4"},
            "body": {"size": "1rem", "weight": "400", "line_height": "1.6"},
            "body_small": {"size": "0.875rem", "weight": "400", "line_height": "1.5"},
            "caption": {"size": "0.75rem", "weight": "400", "line_height": "1.4"},
            "label": {"size": "0.875rem", "weight": "500", "line_height": "1.3"},
        },
    },
    spacing={
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2.25rem",
        "2xl": "3.25rem",
    },
    radius={
        "none": "0px",
        "sm": "4px",
        "md": "8px",
        "lg": "12px",
        "pill": "9999px",
    },
)

PROOFS = [JAPAN_PRINT_INK_DNA, CHAINSAW_MAN_INSPIRED_DNA, MUSHISHI_INSPIRED_DNA]
