"""
MultiMind AI - Real Design DNA Proofs (S6.2 / S8.1 Composition)
Defines asset-enabled Design DNA definitions representing Identity and Web/Information roles.
"""
from ui.dna.models import DesignDNA, MaterialReference, PresentationPolicy

# DNA A — Japan Print / Ink (Identity DNA)
JAPAN_PRINT_INK_DNA = DesignDNA(
    id="japan-print-ink",
    display_name="Japan Print / Ink",
    role="identity",
    category="cultural",
    description="A restrained, print-inspired visual character drawing on ink strokes and warm paper surfaces.",
    reference_identity="Traditional Japanese woodblock printing and high-contrast editorial typography",
    visual_character="restrained, ink-oriented, editorial, tactile paper direction",
    color_direction="warm paper background, dark ink text, restrained cinnabar accents",
    typography_direction="deliberate, high contrast print hierarchy",
    surface_language="paper-like surface and subtle warm borders",
    shape_language="firm, small radii reflecting cut block edges",
    interaction_character="precise, restrained focus and active state contrast",
    materials=[
        MaterialReference(
            id="japan-ink-mark",
            material_type="graphic_mark",
            asset_path="ui/assets/materials/japan-ink-mark/mark.svg",
            source="S6.3 Material Pipeline Proofs",
            author="Programmatically generated SVG for MultiMind AI",
            license="Project-Owned Asset",
            attribution="MultiMind AI Project",
            reference_ip="Traditional Japanese print/ink arts",
            scope_lock=True,
            shared_resource_policy="disallowed",
        )
    ],
    provenance={
        "author": "MultiMind Design Team",
        "license": "Project-Owned Asset",
        "source": "S6.2 Design DNA Proofs",
        "attribution": "Inspired by traditional woodblock and print graphic arts",
    },
    colors={
        "background": "#F5F2EB",
        "surface": "#EAE5D9",
        "surface_elevated": "#DFD9C9",
        "surface_muted": "#F5F2EB",
        "surface_hover": "#E2DCCE",
        "surface_input": "#EFECE2",
        "text": "#121212",
        "text_muted": "#55524C",
        "text_disabled": "#8C8880",
        "primary": "#121212",
        "primary_hover": "#2B2B2B",
        "primary_active": "#000000",
        "secondary": "#55524C",
        "secondary_hover": "#3D3A35",
        "accent": "#C83E2B",  # Cinnabar Red
        "border": "#222222",
        "border_subtle": "#D1CBBF",
        "border_hover": "#121212",
        "border_focus": "#C83E2B",
        "focus_ring": "rgba(200, 62, 43, 0.3)",
        "success": "#2D6A4F",
        "success_bg": "rgba(45, 106, 79, 0.12)",
        "warning": "#B5651D",
        "warning_bg": "rgba(181, 101, 29, 0.12)",
        "danger": "#C83E2B",
        "danger_bg": "rgba(200, 62, 43, 0.12)",
        "info": "#121212",
        "info_bg": "rgba(18, 18, 18, 0.08)",
    },
    typography={
        "font_family_base": "Georgia, 'Times New Roman', Times, serif",
        "font_family_mono": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
        "roles": {
            "display": {"size": "2.125rem", "weight": "700", "line_height": "1.25"},
            "heading": {"size": "1.5rem", "weight": "700", "line_height": "1.3"},
            "subheading": {"size": "1.2rem", "weight": "600", "line_height": "1.35"},
            "body": {"size": "1rem", "weight": "400", "line_height": "1.6"},
            "body_small": {"size": "0.875rem", "weight": "400", "line_height": "1.5"},
            "caption": {"size": "0.75rem", "weight": "400", "line_height": "1.4"},
            "label": {"size": "0.875rem", "weight": "600", "line_height": "1.2"},
        },
    },
    spacing={
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2rem",
        "2xl": "3rem",
    },
    radius={
        "none": "0px",
        "sm": "2px",
        "md": "2px",
        "lg": "4px",
        "pill": "9999px",
    },
)


# DNA B — Chainsaw Man-Inspired (Identity DNA)
CHAINSAW_MAN_INSPIRED_DNA = DesignDNA(
    id="chainsaw-man-inspired",
    display_name="Chainsaw Man Inspired",
    role="identity",
    category="anime",
    description="An aggressive, graphic, poster-like urban visual character with stark contrast and sharp geometry.",
    reference_identity="High-energy manga composition, urban editorial graphic direction, and sharp contrasts",
    visual_character="aggressive, graphic, urban poster, rough, sharp, high contrast",
    color_direction="stark dark asphalt surface, intense safety yellow and visceral red accents",
    typography_direction="assertive, bold, graphic editorial hierarchy",
    surface_language="stark dark slate/asphalt surfaces with razor-sharp borders",
    shape_language="sharp, zero-radius geometry",
    interaction_character="high-contrast assertive interactive states",
    materials=[
        MaterialReference(
            id="chainsaw-hazard-mark",
            material_type="graphic_mark",
            asset_path="ui/assets/materials/chainsaw-hazard-mark/mark.svg",
            source="S6.3 Material Pipeline Proofs",
            author="Programmatically generated SVG for MultiMind AI",
            license="Project-Owned Asset",
            attribution="MultiMind AI Project",
            reference_ip="Generic industrial hazard visual language",
            scope_lock=True,
            shared_resource_policy="disallowed",
        )
    ],
    provenance={
        "author": "MultiMind Design Team",
        "license": "Project-Owned Asset",
        "source": "S6.2 Design DNA Proofs",
        "attribution": "Conceptual interpretation of modern urban action manga visual language",
    },
    colors={
        "background": "#0D0D11",
        "surface": "#16161D",
        "surface_elevated": "#22222E",
        "surface_muted": "#0D0D11",
        "surface_hover": "#2A2A38",
        "surface_input": "#111116",
        "text": "#F2F2F5",
        "text_muted": "#9A9AA6",
        "text_disabled": "#5A5A66",
        "primary": "#FFCC00",  # Caution / Hazard Yellow
        "primary_hover": "#FFE066",
        "primary_active": "#E6B800",
        "secondary": "#9A9AA6",
        "secondary_hover": "#CCCCCC",
        "accent": "#E63946",  # Visceral Red
        "border": "#333344",
        "border_subtle": "#22222E",
        "border_hover": "#FFCC00",
        "border_focus": "#FFCC00",
        "focus_ring": "rgba(255, 204, 0, 0.4)",
        "success": "#10B981",
        "success_bg": "rgba(16, 185, 129, 0.15)",
        "warning": "#FFCC00",
        "warning_bg": "rgba(255, 204, 0, 0.15)",
        "danger": "#E63946",
        "danger_bg": "rgba(230, 57, 70, 0.18)",
        "info": "#FFCC00",
        "info_bg": "rgba(255, 204, 0, 0.12)",
    },
    typography={
        "font_family_base": "'Impact', 'Arial Black', -apple-system, BlinkMacSystemFont, sans-serif",
        "font_family_mono": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
        "roles": {
            "display": {"size": "2.25rem", "weight": "900", "line_height": "1.15"},
            "heading": {"size": "1.5rem", "weight": "800", "line_height": "1.2"},
            "subheading": {"size": "1.25rem", "weight": "700", "line_height": "1.3"},
            "body": {"size": "1rem", "weight": "400", "line_height": "1.45"},
            "body_small": {"size": "0.875rem", "weight": "400", "line_height": "1.4"},
            "caption": {"size": "0.75rem", "weight": "600", "line_height": "1.3"},
            "label": {"size": "0.875rem", "weight": "700", "line_height": "1.2"},
        },
    },
    spacing={
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "0.875rem",
        "lg": "1.25rem",
        "xl": "1.75rem",
        "2xl": "2.5rem",
    },
    radius={
        "none": "0px",
        "sm": "0px",
        "md": "0px",
        "lg": "0px",
        "pill": "0px",
    },
)


# DNA C — Mushishi-Inspired (Identity DNA)
MUSHISHI_INSPIRED_DNA = DesignDNA(
    id="mushishi-inspired",
    display_name="Mushishi Inspired",
    role="identity",
    category="anime",
    description="A calm, organic, atmospheric visual character with muted earth/moss tones and gentle curves.",
    reference_identity="Atmospheric naturalism, quiet organic stillness, and soft muted color palettes",
    visual_character="calm, organic, atmospheric, muted, natural, restrained",
    color_direction="deep forest moss background, muted sage surfaces, calm green tea accents",
    typography_direction="calm, readable, unobtrusive typography",
    surface_language="soft natural surface layering with organic subtle borders",
    shape_language="softer rounded geometry",
    interaction_character="gentle, unobtrusive interactive state transitions",
    materials=[
        MaterialReference(
            id="mushishi-moss-mark",
            material_type="graphic_mark",
            asset_path="ui/assets/materials/mushishi-moss-mark/mark.svg",
            source="S6.3 Material Pipeline Proofs",
            author="Programmatically generated SVG for MultiMind AI",
            license="Project-Owned Asset",
            attribution="MultiMind AI Project",
            reference_ip="Natural atmospheric graphic language",
            scope_lock=True,
            shared_resource_policy="disallowed",
        )
    ],
    provenance={
        "author": "MultiMind Design Team",
        "license": "Project-Owned Asset",
        "source": "S6.2 Design DNA Proofs",
        "attribution": "Conceptual interpretation of naturalistic anime atmospheric art",
    },
    colors={
        "background": "#111814",
        "surface": "#1D2822",
        "surface_elevated": "#293830",
        "surface_muted": "#111814",
        "surface_hover": "#24322A",
        "surface_input": "#16201B",
        "text": "#E2EBE5",
        "text_muted": "#91A398",
        "text_disabled": "#5A6B60",
        "primary": "#7A9A8B",  # Muted Green Tea
        "primary_hover": "#8EAFA0",
        "primary_active": "#668576",
        "secondary": "#91A398",
        "secondary_hover": "#B0C2B7",
        "accent": "#A3B899",  # Soft Pale Moss Accent",
        "border": "#2C3E34",
        "border_subtle": "#1D2822",
        "border_hover": "#3F5649",
        "border_focus": "#7A9A8B",
        "focus_ring": "rgba(122, 154, 139, 0.3)",
        "success": "#668576",
        "success_bg": "rgba(102, 133, 118, 0.15)",
        "warning": "#C2A675",
        "warning_bg": "rgba(194, 166, 117, 0.15)",
        "danger": "#B86B6B",
        "danger_bg": "rgba(184, 107, 107, 0.15)",
        "info": "#7A9A8B",
        "info_bg": "rgba(122, 154, 139, 0.12)",
    },
    typography={
        "font_family_base": "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
        "font_family_mono": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
        "roles": {
            "display": {"size": "2rem", "weight": "500", "line_height": "1.3"},
            "heading": {"size": "1.5rem", "weight": "500", "line_height": "1.35"},
            "subheading": {"size": "1.25rem", "weight": "500", "line_height": "1.4"},
            "body": {"size": "1rem", "weight": "400", "line_height": "1.6"},
            "body_small": {"size": "0.875rem", "weight": "400", "line_height": "1.5"},
            "caption": {"size": "0.75rem", "weight": "400", "line_height": "1.4"},
            "label": {"size": "0.875rem", "weight": "500", "line_height": "1.3"},
        },
    },
    spacing={
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2.25rem",
        "2xl": "3.25rem",
    },
    radius={
        "none": "0px",
        "sm": "4px",
        "md": "8px",
        "lg": "12px",
        "pill": "9999px",
    },
)


# DNA D — Rinpa Decorative Spatial (Identity DNA Proof)
RINPA_DECORATIVE_SPATIAL_DNA = DesignDNA(
    id="rinpa-decorative-spatial",
    display_name="Rinpa Decorative Spatial",
    role="identity",
    category="cultural",
    description="A decorative, spatial visual identity featuring deliberate asymmetry, negative space tension, and mineral/gold accents.",
    reference_identity="Traditional Japanese Rinpa school screen paintings, gold foil spatial composition, and organic asymmetry",
    visual_character="decorative spatial composition, deliberate asymmetry, negative space ownership, restrained focal ornament",
    color_direction="warm aged-silk surface, dark ink foundation, gold foil and mineral pigment accents",
    typography_direction="deliberate, elegant hierarchy with serif elegance",
    surface_language="gilded silk surface layering with delicate warm golden borders",
    shape_language="organic subtle curves with asymmetric framing",
    interaction_character="refined, deliberate focus state transitions with mineral gold highlights",
    materials=[
        MaterialReference(
            id="rinpa-gold-mark",
            material_type="graphic_mark",
            asset_path="ui/assets/materials/rinpa-gold-mark/mark.svg",
            source="Composition Contract Proofs",
            author="Programmatically generated SVG for MultiMind AI",
            license="Project-Owned Asset",
            attribution="MultiMind AI Project",
            reference_ip="Traditional Japanese Rinpa decorative arts",
            scope_lock=True,
            shared_resource_policy="disallowed",
        )
    ],
    provenance={
        "author": "MultiMind Design Team",
        "license": "Project-Owned Asset",
        "source": "Composition Contract Proofs",
        "attribution": "Inspired by Rinpa school gold leaf screen compositions and natural motifs",
    },
    colors={
        "background": "#F2ECE1",
        "surface": "#E6DEC8",
        "surface_elevated": "#DCD2B7",
        "surface_muted": "#F2ECE1",
        "surface_hover": "#DDD4BC",
        "surface_input": "#ECE5D5",
        "text": "#1A1714",
        "text_muted": "#5C5449",
        "text_disabled": "#948A7B",
        "primary": "#B8860B",  # Mineral Gold Leaf
        "primary_hover": "#966C05",
        "primary_active": "#735200",
        "secondary": "#5C5449",
        "secondary_hover": "#3D372F",
        "accent": "#2E5A44",  # Malachite Green Mineral Accent
        "border": "#2B241C",
        "border_subtle": "#CDC2A8",
        "border_hover": "#B8860B",
        "border_focus": "#B8860B",
        "focus_ring": "rgba(184, 134, 11, 0.35)",
        "success": "#2E5A44",
        "success_bg": "rgba(46, 90, 68, 0.12)",
        "warning": "#B8860B",
        "warning_bg": "rgba(184, 134, 11, 0.12)",
        "danger": "#A63A2B",
        "danger_bg": "rgba(166, 58, 43, 0.12)",
        "info": "#1A1714",
        "info_bg": "rgba(26, 23, 20, 0.08)",
    },
    typography={
        "font_family_base": "Georgia, 'Times New Roman', serif",
        "font_family_mono": "'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, Courier, monospace",
        "roles": {
            "display": {"size": "2.25rem", "weight": "700", "line_height": "1.2"},
            "heading": {"size": "1.5rem", "weight": "700", "line_height": "1.3"},
            "subheading": {"size": "1.2rem", "weight": "600", "line_height": "1.35"},
            "body": {"size": "1rem", "weight": "400", "line_height": "1.6"},
            "body_small": {"size": "0.875rem", "weight": "400", "line_height": "1.5"},
            "caption": {"size": "0.75rem", "weight": "400", "line_height": "1.4"},
            "label": {"size": "0.875rem", "weight": "600", "line_height": "1.2"},
        },
    },
    spacing={
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1rem",
        "lg": "1.5rem",
        "xl": "2.25rem",
        "2xl": "3.5rem",
    },
    radius={
        "none": "0px",
        "sm": "3px",
        "md": "4px",
        "lg": "6px",
        "pill": "9999px",
    },
)


# DNA E — Japan High-Density Information (Web / Information DNA Proof)
JAPAN_HIGH_DENSITY_INFO_DNA = DesignDNA(
    id="japan-high-density-info",
    display_name="Japan High-Density Information",
    role="web_information",
    category="cultural_web",
    description="A secondary information design character emphasizing metadata prominence, status richness, and compact utility grouping.",
    reference_identity="Japanese modern utility web portals, high-density dashboard layouts, and information-rich metadata displays",
    visual_character="high-density metadata, rich status indicators, efficient utility grouping, clear secondary hierarchy",
    color_direction="secondary status richness with distinct badge contrast",
    typography_direction="compact readable metadata scales",
    surface_language="compact structured utility groupings",
    shape_language="compact functional radii",
    interaction_character="compact rapid status feedback",
    presentation_policy=PresentationPolicy(
        metadata_prominence="high",
        status_richness="rich",
        navigation_density="compact",
        secondary_compactness=True,
        information_discoverability="enhanced",
        utility_grouping="structured",
    ),
    materials=[],
    provenance={
        "author": "MultiMind Design Team",
        "license": "Project-Owned Asset",
        "source": "Composition Contract Proofs",
        "attribution": "Inspired by information-rich Japanese modern web portal architecture",
    },
    colors={},
    typography={},
    spacing={},
    radius={},
)

PROOFS = [
    JAPAN_PRINT_INK_DNA,
    CHAINSAW_MAN_INSPIRED_DNA,
    MUSHISHI_INSPIRED_DNA,
    RINPA_DECORATIVE_SPATIAL_DNA,
    JAPAN_HIGH_DENSITY_INFO_DNA,
]
